line_light_detector:
  ros__parameters:
    image_topic: '/video_source/raw'
    roi_y_start:     0.4
    trap_top_ratio:  0.9
    x_crop_ratio:    0.2
    morph_kernel_size: 3
    morph_iterations:  2
    use_clahe:        true

yolov8_detector:
  ros__parameters:
    model_path:              '/home/jp/ros2_ws_2/src/puzzlebot_line_follower/models/lastfinal.pt'
    image_topic:             '/video_source/raw'
    confidence_threshold:     0.6
    inference_topic:         '/yolov8/inference'
    annotated_image_topic:   '/inference_result'

line_follower_controller:
  ros__parameters:
    error_topic:      '/line_detector/error'
    cmd_vel_topic:    '/cmd_vel'
    loop_hz:           10.0
    Kp:                1.2
    Ki:                0.0
    Kd:                0.15
    v_default:         0.15
    v_caution_factor:  0.5
    max_angular_vel:   1.0
